name: flutter_qiblah
description: Flutter Qiblah is a package that allows you to display Qiblah direction in you app with support for both Android and iOS
version: 2.0.2
homepage: https://github.com/medyas/flutter_qiblah

environment:
  sdk: ">=2.12.0 <3.0.0"

  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_compass: #^0.7.0 # Here the git ref is used because current 0.7.0 forces android min sdk to be 23
    git:
      url: https://github.com/hemanthrajv/flutter_compass.git
      ref: 14e134f0aed3c9fe09065bea05281f2c26f171d1
  geolocator: ^7.6.0
  stream_transform: ^2.0.0
  vector_math: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: ml.medyas.flutter_qiblah
        pluginClass: FlutterQiblahPlugin
      ios:
        pluginClass: FlutterQiblahPlugin
